fix

diff --git a/.github/workflows/_ccw.yml b/.github/workflows/_ccw.yml
--- a/.github/workflows/_ccw.yml
+++ b/.github/workflows/_ccw.yml
@@ -30,8 +30,12 @@ jobs:
     runs-on: ${{ inputs.platform }}
     steps:
       - uses: actions/checkout@v4
+      - name: List directory contents
+        run: ls -la
+      - name: Check if Cargo.toml exists
+        run: test -f ./Cargo.toml && echo "Cargo.toml found" || echo "Cargo.toml not found"
       - name: Set LTO to true
-        run: sed -i 's/lto = false/lto = true/g' Cargo.toml
+        run: sed -i 's/lto = false/lto = true/g' ./Cargo.toml
       - uses: taiki-e/upload-rust-binary-action@v1.18.0
         with:
           bin: ${{ inputs.binary }}
